#服务器配置
server:
  port: 8080  # 修改端口为8081

spring:
  #数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/management
    username: root
    password: 1234
  #文件上传信息
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB

#允许的文件类型
document:
  allowed-types: pdf,doc,docx,xls,xlsx,ppt,pptx,txt,jpg,png,jpeg,gif,zip,rar


# 允许的头像文件类型
avatar:
  allowed-types: jpg,png,jpeg

#阿里云OSS配置
aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: ${ALIYUN_ACCESS_KEY_ID}
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET}
    bucket-name: web-konnac-management
    base-url: https://web-konnac-management.oss-cn-hangzhou.aliyuncs.com/


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
    jdbc-type-for-null: 'null'
#spring事务管理日志 作用: 配置spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
    com.github.pagehelper: WARN
    com.konnac.mapper: DEBUG
